# Generated by Django 2.1.4 on 2019-03-03 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='文章内容',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题', models.CharField(max_length=70)),
                ('正文', models.TextField()),
                ('创建时间', models.DateField()),
                ('摘要', models.CharField(blank=True, max_length=100)),
                ('作者', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='文章分类',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('类名', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='文章标签',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标签名', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='文章内容',
            name='分类',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.文章分类'),
        ),
        migrations.AddField(
            model_name='文章内容',
            name='标签',
            field=models.ManyToManyField(blank=True, to='myblog.文章标签'),
        ),
    ]
