# Generated by Django 2.1.4 on 2019-03-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190303_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='评论',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('评论者', models.CharField(max_length=20)),
                ('评论日期', models.DateField(auto_now_add=True)),
                ('评论时间', models.TimeField(auto_now_add=True)),
                ('评论内容', models.TextField()),
                ('对应文章', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.文章内容')),
            ],
        ),
    ]
